stages:
- test
- cov

default:
  image: python3
  
testing:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
    - tox -p

coverage_test:
  stage: cov
  script:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
    - pytest --cov=biquat_py tests
  artifacts:
    when: always
    reports: 
      junit: report.xml
    paths:
      - "report.xml"
    expire_in: 1 week

  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
