stages:
- test
- flake
- cov

testing:
  stage: test
  image:
    name: $IMAGE
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - pip install -r requirements_dev.txt
    - pip install -r requirements.txt
    - tox -e python3
  parallel:
    matrix:
      - IMAGE: [python:3.11-bullseye,python:3.10-bullseye,python:3.9-bullseye,python:3.8-bullseye]

flaking:
  stage: flake
  image:
    name: python:3.11-bullseye
  script:
    - pip install -r requirements_dev.txt
    - pip install -r requirements.txt
    - tox -e flake8

coverage_test:
  stage: cov
  image:
    name: python:3.11-bullseye
  script:
    - pip install -r requirements_dev.txt
    - pip install -r requirements.txt
    - tox -e cov
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
