stages:
- test
- cov

testing:
  stage: test
  script:
    - tox -p

coverage_test:
  stage: cov
  script:
    - pytest --cov=biquat_py tests
  artifacts:
    when: always
    reports: 
      junit: report.xml
    paths:
      - "report.xml"
    expire_in: 1 week
    
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
