
stages:
- test
- cov


testing:
  stage: test
  image:
    name: $IMAGE
  script:
    - pip install -r requirements_dev.txt
    - tox -p
  parallel:
    matrix:
      - IMAGE: [python:3.11,python:3.10,python:3.9,python:3.8]

coverage_test:
  stage: cov
  image:
    name: python:latest
  script:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
    - pytest --cov=biquat_py tests
  artifacts:
    when: always
    reports: 
      junit: report.xml
    paths:
      - "report.xml"
    expire_in: 1 week

  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
