stages:
- test
- flake
- cov

testing:
  stage: test
  image:
    name: $IMAGE
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - pip install tox
    - tox -e python3
  parallel:
    matrix:
      - IMAGE: [python:bullseye]

flaking:
  stage: flake
  image:
    name: python:bullseye
  script:
    - pip install -r tox
    - tox -e flake8

coverage_test:
  stage: cov
  image:
    name: python:bullseye
  script:
    - pip install -r tox
    - tox -e cov
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
